import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "../components/Layout/Navbar";
import { Playfair_Display } from "next/font/google";
import AuthComponent from "~/components/Layout/AuthComponent";

const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BalkanDad Chess",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${playfair.className}`}>
      <body>
        <TRPCReactProvider>
          <Navbar authComponent={<AuthComponent />} />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
